"""atualização tabela docuemntos

Revision ID: d792ca1fd9c2
Revises: 3eff6cba54bf
Create Date: 2025-09-27 21:43:07.913716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd792ca1fd9c2'
down_revision: Union[str, Sequence[str], None] = '3eff6cba54bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_fii',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_documento', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('id_sigla_fundo', sa.Integer(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_sigla_fundo'], ['fundos_imobiliarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento')
    )
    op.drop_table('documentos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_documento', sa.VARCHAR(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(), nullable=False),
    sa.Column('id_sigla_fundo', sa.INTEGER(), nullable=True),
    sa.Column('data_entrega', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_sigla_fundo'], ['fundos_imobiliarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_documento')
    )
    op.drop_table('documentos_fii')
    # ### end Alembic commands ###
